// node scripts/build.mjs
//
// 1. Reads data/muslim.json  (source of truth — always preferred)
// 2. Compresses to data/muslim.json.gz  (always recompresses — never stale)
// 3. Splits into data/chapters/  (one file per chapter)
// 4. Writes src/index.browser.js

import fs   from 'fs';
import zlib from 'zlib';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, '..');
const dataDir   = path.join(ROOT, 'data');
const jsonPath  = path.join(dataDir, 'muslim.json');
const gzPath    = path.join(dataDir, 'muslim.json.gz');

// ── Step 1: Load data/muslim.json ─────────────────────────────────────────────
if (!fs.existsSync(jsonPath)) {
  throw new Error('data/muslim.json not found. Place your muslim.json in the data/ folder.');
}
console.log('✓ Reading data/muslim.json ...');
const raw  = fs.readFileSync(jsonPath);
const data = JSON.parse(raw.toString('utf8'));
console.log(`  hadiths : ${data.hadiths.length.toLocaleString()}`);
console.log(`  chapters: ${data.chapters.length.toLocaleString()}`);
console.log('');

// ── Step 2: Always recompress json → gz ───────────────────────────────────────
console.log('✓ Compressing data/muslim.json → data/muslim.json.gz ...');
const compressed = zlib.gzipSync(raw, { level: 9 });
fs.writeFileSync(gzPath, compressed);
console.log(`  before : ${(raw.length        / 1024 / 1024).toFixed(2)} MB`);
console.log(`  after  : ${(compressed.length / 1024 / 1024).toFixed(2)} MB`);
console.log(`  saved  : ${((1 - compressed.length / raw.length) * 100).toFixed(0)}%`);
console.log('');

// ── Step 3: Split into data/chapters/ ─────────────────────────────────────────
const chaptersDir = path.join(dataDir, 'chapters');
if (!fs.existsSync(chaptersDir)) fs.mkdirSync(chaptersDir, { recursive: true });

fs.writeFileSync(
  path.join(chaptersDir, 'meta.json'),
  JSON.stringify({ metadata: data.metadata, chapters: data.chapters, total: data.hadiths.length }),
  'utf8'
);
const byChapter = {};
data.hadiths.forEach(h => {
  if (!byChapter[h.chapterId]) byChapter[h.chapterId] = [];
  byChapter[h.chapterId].push(h);
});
let count = 0;
for (const [id, hadiths] of Object.entries(byChapter)) {
  fs.writeFileSync(path.join(chaptersDir, `${id}.json`), JSON.stringify(hadiths), 'utf8');
  count++;
}
console.log(`✓ Written ${count} chapter files → data/chapters/`);
console.log('');

// ── Step 4: Generate src/index.browser.js ─────────────────────────────────────
const version  = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version;
const CDN_FILE = `https://cdn.jsdelivr.net/npm/sahih-muslim@${version}/data/muslim.json.gz`;

const browserSrc = [
  `// AUTO-GENERATED by scripts/build.mjs — do not edit manually`,
  `// sahih-muslim v${version}`,
  `// Fetches data/muslim.json.gz from CDN. Works in React, Vue, Vite, webpack.`,
  ``,
  `const CDN_FILE = '${CDN_FILE}';`,
  ``,
  `function _build(hadiths, meta) {`,
  `  return Object.assign([], hadiths, {`,
  `    metadata:     meta.metadata,`,
  `    chapters:     meta.chapters,`,
  `    getByChapter: (id) => hadiths.filter(h => h.chapterId === id),`,
  `    get:          (id) => hadiths.find(h => h.id === id),`,
  `    search: (q, limit = 0) => {`,
  `      const ql = q.toLowerCase();`,
  `      const r  = hadiths.filter(h =>`,
  `        h.english?.text?.toLowerCase().includes(ql) ||`,
  `        h.english?.narrator?.toLowerCase().includes(ql)`,
  `      );`,
  `      return limit > 0 ? r.slice(0, limit) : r;`,
  `    },`,
  `    getRandom: () => hadiths[Math.floor(Math.random() * hadiths.length)],`,
  `  });`,
  `}`,
  ``,
  `export class Muslim {`,
  `  constructor(data) { return _build(data.hadiths, data); }`,
  `}`,
  ``,
  `let _cache = null, _promise = null;`,
  ``,
  `export function loadMuslim() {`,
  `  if (_cache)   return Promise.resolve(_cache);`,
  `  if (_promise) return _promise;`,
  `  _promise = fetch(CDN_FILE)`,
  `    .then(r => r.arrayBuffer())`,
  `    .then(buf => {`,
  `      const stream = new DecompressionStream('gzip');`,
  `      const writer = stream.writable.getWriter();`,
  `      const reader = stream.readable.getReader();`,
  `      writer.write(new Uint8Array(buf));`,
  `      writer.close();`,
  `      const chunks = [];`,
  `      return (function pump() {`,
  `        return reader.read().then(({ done, value }) => {`,
  `          if (done) {`,
  `            const text = new TextDecoder().decode(`,
  `              new Uint8Array(chunks.reduce((a, b) => [...a, ...b], []))`,
  `            );`,
  `            const data = JSON.parse(text);`,
  `            _cache = _build(data.hadiths, data);`,
  `            return _cache;`,
  `          }`,
  `          chunks.push(value);`,
  `          return pump();`,
  `        });`,
  `      })();`,
  `    });`,
  `  return _promise;`,
  `}`,
  ``,
  `export default loadMuslim();`,
].join('\n');

fs.writeFileSync(path.join(ROOT, 'src', 'index.browser.js'), browserSrc, 'utf8');
console.log('✓ Written src/index.browser.js');
console.log('');

// ── Step 5: Copy .gz into python/sahih_muslim/data/ ──────────────────────────
// This makes Poetry include it in the wheel when running python -m build
const pyDataDir = path.join(ROOT, 'python', 'sahih_muslim', 'data');
fs.mkdirSync(pyDataDir, { recursive: true });
fs.copyFileSync(gzPath, path.join(pyDataDir, 'muslim.json.gz'));
console.log('✓ Copied muslim.json.gz → python/sahih_muslim/data/');
console.log('');
console.log('Build complete!');
