// node scripts/build.mjs
// 1. Reads data/tirmidhi.json  (source of truth)
// 2. Compresses to data/tirmidhi.json.gz  (always recompresses)
// 3. Splits into data/chapters/
// 4. Writes src/index.browser.js
// 5. Copies .gz into python/jami_al_tirmidhi/data/ for wheel bundling

import fs   from 'fs';
import zlib from 'zlib';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, '..');
const dataDir   = path.join(ROOT, 'data');
const jsonPath  = path.join(dataDir, 'tirmidhi.json');
const gzPath    = path.join(dataDir, 'tirmidhi.json.gz');

if (!fs.existsSync(jsonPath)) throw new Error('data/tirmidhi.json not found. Place your tirmidhi.json in the data/ folder.');
console.log('OK Reading data/tirmidhi.json ...');
const raw  = fs.readFileSync(jsonPath);
const data = JSON.parse(raw.toString('utf8'));
console.log('  hadiths : ' + data.hadiths.length.toLocaleString());
console.log('  chapters: ' + data.chapters.length.toLocaleString());
console.log('');

console.log('OK Compressing data/tirmidhi.json -> data/tirmidhi.json.gz ...');
const compressed = zlib.gzipSync(raw, { level: 9 });
fs.writeFileSync(gzPath, compressed);
console.log('  before : ' + (raw.length / 1024 / 1024).toFixed(2) + ' MB');
console.log('  after  : ' + (compressed.length / 1024 / 1024).toFixed(2) + ' MB');
console.log('  saved  : ' + ((1 - compressed.length / raw.length) * 100).toFixed(0) + '%');
console.log('');

const chaptersDir = path.join(dataDir, 'chapters');
if (!fs.existsSync(chaptersDir)) fs.mkdirSync(chaptersDir, { recursive: true });
fs.writeFileSync(path.join(chaptersDir, 'meta.json'), JSON.stringify({ metadata: data.metadata, chapters: data.chapters, total: data.hadiths.length }), 'utf8');
const byChapter = {};
data.hadiths.forEach(h => { if (!byChapter[h.chapterId]) byChapter[h.chapterId] = []; byChapter[h.chapterId].push(h); });
let count = 0;
for (const [id, hadiths] of Object.entries(byChapter)) { fs.writeFileSync(path.join(chaptersDir, id + '.json'), JSON.stringify(hadiths), 'utf8'); count++; }
console.log('OK Written ' + count + ' chapter files -> data/chapters/');
console.log('');

const version  = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version;
const CDN_FILE = 'https://cdn.jsdelivr.net/npm/jami-al-tirmidhi@' + version + '/data/tirmidhi.json.gz';
const browserSrc = [
  '// AUTO-GENERATED by scripts/build.mjs -- do not edit manually',
  '// jami-al-tirmidhi v' + version,
  "const CDN_FILE = '" + CDN_FILE + "';",
  "function _build(hadiths, meta) { return Object.assign([], hadiths, { metadata: meta.metadata, chapters: meta.chapters, getByChapter: (id) => hadiths.filter(h => h.chapterId === id), get: (id) => hadiths.find(h => h.id === id), search: (q, limit = 0) => { const ql = q.toLowerCase(); const r = hadiths.filter(h => h.english?.text?.toLowerCase().includes(ql) || h.english?.narrator?.toLowerCase().includes(ql)); return limit > 0 ? r.slice(0, limit) : r; }, getRandom: () => hadiths[Math.floor(Math.random() * hadiths.length)], }); }",
  'export class Tirmidhi { constructor(data) { return _build(data.hadiths, data); } }',
  'let _cache = null, _promise = null;',
  "export function loadTirmidhi() { if (_cache) return Promise.resolve(_cache); if (_promise) return _promise; _promise = fetch(CDN_FILE).then(r => r.arrayBuffer()).then(buf => { const stream = new DecompressionStream('gzip'); const writer = stream.writable.getWriter(); const reader = stream.readable.getReader(); writer.write(new Uint8Array(buf)); writer.close(); const chunks = []; return (function pump() { return reader.read().then(({ done, value }) => { if (done) { const text = new TextDecoder().decode(new Uint8Array(chunks.reduce((a,b)=>[...a,...b],[]))); const data = JSON.parse(text); _cache = _build(data.hadiths, data); return _cache; } chunks.push(value); return pump(); }); })(); }); return _promise; }",
  'export default loadTirmidhi();',
].join('\n');
fs.writeFileSync(path.join(ROOT, 'src', 'index.browser.js'), browserSrc, 'utf8');
console.log('OK Written src/index.browser.js');
console.log('');

const pyDataDir = path.join(ROOT, 'python', 'jami_al_tirmidhi', 'data');
fs.mkdirSync(pyDataDir, { recursive: true });
fs.copyFileSync(gzPath, path.join(pyDataDir, 'tirmidhi.json.gz'));
console.log('OK Copied tirmidhi.json.gz -> python/jami_al_tirmidhi/data/');
console.log('');
console.log('Build complete!');
